// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Dev141","status":true,"description":"DEV funcs for testing and debbung new plugins.","parameters":{"Show Console":"false","Skip Title":"true","Mobile":"false","Build":"false","Plugin":""}},
{"name":"SocketIO","status":true,"description":"v2.0.4 - Socket.IO (for Alpha NET plugin)","parameters":{}},
{"name":"Alpha_NET_build","status":true,"description":"v0.7.900 Network system (Beta)","parameters":{"Alpha NET":"","GameMode":"Multiplayer","ActorsForPlayers":"1, 3, 2, 4","NetworkEvents":"--- --- --- --- ---","ServerStarted":"9","OnConnect":"10","OnDisconect":"13","OnOtherCon":"11","OnOtherDisc":"12","OnPvPEnd":"14","NetworkUI":"--- --- --- --- ---","NameplatesMode":"Others","_supporters":"Thanks to these guys!","Donald Derrick":"","Ilya Chkoliar":"https://elushisgaming.club/","Kevin Sjöberg":"","Sarcastic Sloth":"https://sarcasticsloth42.wixsite.com/avillainstale","Plerai":""}}
];
